package.json, public/index.html, server.js
part of https://github.com/hoodiehq/camp/issues/105
=> Version 1 bot, steps 1-5

package.json, server.js
I’m creating a screencast as I go so you can follow it and merge later :)
=> add standard

.travis.yml
@gr2m Not sure if I did this right. Can you please review? 
I turned on travis on the repo.
=> create travis file

lib/create-issue.js, lib/get-branch.js, lib/get-commit.js, lib/handle-create-event.js, package.json, server.js, test/integration/server-test.js, test/integration/smoke-test.js, test/unit/get-branch-test.js
I’ve made a screencast if you want to follow along. It’s rather long and probly 2/3 of the time I’m confused (I’m really tired today) but maybe you can at least skim through it and leart a trick or two :)
Exporting takes 3h and uploading will take another 30min or so.
closes #81
=> modularization and tests

.gitignore, lib/create-issue.js, lib/get-branch.js, lib/get-commit.js, lib/handle-create-event.js, package.json, server.js, test/integration/server-test.js, test/unit/get-branch-test.js
This should help us understand better if things don’t work as expected
=> debug logs

lib/handle-create-event.js
so we don’t pollute https://twitter.com/first_tmrs_only
=> fix: change default label to first-timers-only-testing until release

package.json
not very elegant solution, but it sets the `DEBUG` environment variable for [debug](https://www.npmjs.com/package/debug). This will make it easier for us to debug the bot if something is not working properly
=> log debug info on now

lib/create-issue.js, test/unit/create-issue-test.js
@Techforchange is currently working on tests.
=> WIP - Creates unit test for createIssue

test/unit/create-issue-test.js
=> Creates issue failure test

lib/handle-create-event.js, server.js
=> chore: remove word to shorten debug logs

README.md, lib/create-issue.js, lib/handle-create-event.js, test/integration/server-test.js, test/unit/create-issue-test.js
User is able to configure the labels and the repo the issue is created on. I am currently working on tests. And then will do another PR for the readme instructions.
=> Feature: add configurable labels and repository

package.json
=> fix(package): update probot to version 1.1.0

lib/create-issue.js, lib/get-branch.js, lib/get-commit.js, lib/get-template-content.js, lib/handle-create-event.js, test/unit/create-issue-test.js, test/unit/get-branch-test.js, test/unit/get-commit-test.js, test/unit/get-template-content-test.js
The current implementation is broken
=> 🐛 Create issue on configured repository

instructions.md
changing "assign yourself to this repository" to "assign yourself to this issue"
fixes https://github.com/hoodiehq/first-timers-bot/issues/154
=> fixing typo in instructions

instructions.md
Added few lines for better understanding
closes https://github.com/hoodiehq/camp/issues/129
=> Updated instructions.md file

.github/first-timers.yml, README.md, instructions.md, lib/handle-create-event.js
time to remove you from our default configurations, see you again next year :)
closes #172
=> Goodbye Hacktoberfest

lib/delete-branch.js, lib/handle-create-event.js, test/unit/delete-branch-test.js
Once a new issue is created, the `first-timers-` branch that triggered the issue creation will be deleted.
Fixes #123
=> feat: delete `first-timers-` branch after issue creation

package.json
Updates Node to latest version 8. @gr2m
=> fix(package): update node to version 8.x

lib/create-issue.js, test/unit/create-issue-test.js
Adds a `$ISSUE_NUMBER` variable to issue creation templates so people can reference issue numbers in their templates :)
Fixes #153
=> feat: add $ISSUE_NUMBER value to issue creation template

README.pt_br.md, instructions.pt_br.md
I translated the content of the README.md file to Brazilian Portuguese in a new file called README.pt_br.md
=> README Translation to Brazilian Portuguese

package.json
=> fix(package): update probot to version 9.0.0

package.json
=> chore(package): update tap to version 13.0.1

package.json, server.js
=> chore(package): update standard to version 14.0.2

README.md, README.pt_br.md, instructions.md, instructions.pt_br.md, lib/create-issue.js, lib/delete-branch.js, lib/get-branch.js, lib/get-commit.js, lib/get-template-content.js, lib/handle-create-event.js, package.json, test/integration/server-test.js, test/integration/smoke-test.js, test/unit/create-issue-test.js, test/unit/delete-branch-test.js, test/unit/get-branch-test.js, test/unit/get-commit-test.js, test/unit/get-template-content-test.js
I am working on the up to ugrade it to the upcoming Probot v10. This makes it much easier for me
=> replace standard with prettier

README.md, lib/create-issue.js, test/unit/create-issue-test.js
=> feat: `$COMMIT_BODY` placeholder

README.md, lib/get-template-content.js, lib/handle-create-event.js, test/unit/get-template-content-test.js
=> feat: load template from different repository
